site_name: edi.substanceforms

nav:
    - Home: index.md
    - Ausgangssituation: ausgang.md
    - Zielsetzung: zielsetzung.md
    - Anforderungsanalye: anforderungen.md  
    - Bestandteile der Applikation: bestandteile.md
    - Anwendungsarchitektur: aufbau.md
    - Installation und Konfiguration im CMS Plone: plone.md
    - Automatische Testverfahren: tests.md
    - Lizenz: lizenz.md  
    - Anhang:
        - 'Anhang 1: ERM-Datenbankmodell': anhang1.md
        - 'Anhang 2: Aktivitätendiagramm Gefahrstoffgemisch hinzufügen': anhang2.md
        - 'Anhang 3: Verzeichnis Funktionstests': anhang3.md
        - 'Anhang 4: Abkürzungsverzeichnis': anhang4.md
        - 'Anhang 5: Sequenzdiagramm Bildbehandlung': anhang5.md

theme: material     

plugins:
    - search
    - with-pdf:
        author: Seppo Walther
        copyright: Creative Commons (CC BY 4.0)
        cover_subtitle: Technische Dokumentation
        toc_title: Inhaltsverzeichnis

markdown_extensions:
  - abbr
  - pymdownx.snippets
