site_name: edi.substanceforms

nav:
    - Home: index.md
    - Änderungsnachweis: aenderungen.md
    - Ausgangssituation: ausgang.md
    - Zielsetzung: zielsetzung.md
    - Anforderungsanalye: anforderungen.md  
    - Bestandteile der Applikation: bestandteile.md
    - Anwendungsarchitektur: aufbau.md
    - Installation und Konfiguration im CMS Plone: plone.md
    - Automatische Testverfahren: tests.md
    - Lizenz: lizenz.md  
    - Anhang:
        - 'Anhang 1: ERM-Datenbankmodell': anhang1.md
        - 'Anhang 2: Aktivitätendiagramm Gefahrstoffgemisch hinzufügen': anhang2.md
        - 'Anhang 3: Verzeichnis Funktionstests': anhang3.md
        - 'Anhang 4: Abkürzungsverzeichnis': anhang4.md
        - 'Anhang 5: Sequenzdiagramm Bildbehandlung': anhang5.md
        - 'Anhang 6: Klassendiagramme Plone-System': anhang6.md

theme: material     

plugins:
    - search
    - with-pdf:
        author: Seppo Walther
        copyright: (c) Seppo Walther -edi.substanceforms-
        cover_subtitle: Dokumentation des Projekts 
        toc_title: Inhaltsverzeichnis

extra:
    cover_description: Winterprüfung 2021
    cover_additional: Fachinformatiker Anwendungsentwicklung
    cover_company: educorvi GmbH & Co. KG
    cover_street: Karolinenstraße 17
    cover_zip_location: 90763 Fürth
    cover_url: https://www.educorvi.de
    cover_www: www.educorvi.de
    cover_name: Seppo Walther
    cover_copyright: CC BY 4.0
    cover_date: 08.12.2021  

markdown_extensions:
  - abbr
  - pymdownx.snippets
