site_name: edi.substanceforms

nav:
    - Home: index.md
    - Ausgangssituation: ausgang.md
    - Zielsetzung: zielsetzung.md
    - Anforderungsanalye: anforderungen.md  
    - Bestandteile der Applikation: bestandteile.md
    - Aufbau des Software-Packages: aufbau.md
    - Automatische Testverfahren: tests.md
    - Installation und Konfiguration im CMS Plone: plone.md
    - Lizenz: lizenz.md  
    - Anhang: anhang.md

theme: material     

plugins:
    - search
    - with-pdf:
        author: Seppo Walther
        copyright: Creative Commons (CC BY-ND)
        cover_subtitle: Projektarbeit Seppo Walther
        toc_title: Inhaltsverzeichnis

markdown_extensions:
  - abbr
  - pymdownx.snippets
